### PR TITLE
vod - add ability to query and filter files for camera based on time

### PR DESCRIPTION
**Pull request by stephengolub**
Hey, just sharing my thoughts in code.

### CODE REVIEW

**Comment by hunterjm** [comment]
Nice. Have you tested this? Does `nginx-vod-module` pass those query string params along? I'm a little worried about the implications this could have performance wise when someone is saving months worth of recordings.

**Comment by stephengolub** [comment]
This hasn't been integration tested, just shown as the possibility. It'd be nice if we could pass info through nginx to this, although my familiarity with nginx VOD is pretty much limited to what you've built.

My opinion would be do something like this under the hood, then make the calls adapt for forward looking capabilities.

**Comment by hunterjm** [comment]
> This hasn't been integration tested, just shown as the possibility. It'd be nice if we could pass info through nginx to this, although my familiarity with nginx VOD is pretty much limited to what you've built.
> 
> My opinion would be do something like this under the hood, then make the calls adapt for forward looking capabilities.

Will test later today.

**Comment by stephengolub** [comment]
If you've got a good example of how to test this well, I'm willing to spend some time on it.

**Comment by hunterjm** [comment]
Closing in favor of implementing something else to handle this at a future date per conversation in the other PR.

**Pull request closed without merging**
